export const ERROR_CODES = {
    // --- CLIENT ERRORS (4xx) ---
    BAD_REQUEST: "BAD_REQUEST",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",

    // --- SERVER ERRORS (5xx) ---
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    DATABASE_ERROR: "DATABASE_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    UPSTREAM_ERROR: "UPSTREAM_ERROR",
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
