export const ERROR_CODES = {
// 1. SYSTEM ERRORS (Infrastructure, DB, Upstream)
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    DATABASE_ERROR: "DATABASE_ERROR",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
    TIMEOUT: "TIMEOUT",

    // 2. SECURITY ERRORS (Auth, Permissions)
    UNAUTHORIZED: "UNAUTHORIZED",           // 401
    FORBIDDEN: "FORBIDDEN",                 // 403
    TOKEN_EXPIRED: "TOKEN_EXPIRED",         // 401
    INVALID_TOKEN: "INVALID_TOKEN",         // 401

    // 3. VALIDATION/CLIENT ERRORS (Bad Input, Business Logic)
    BAD_REQUEST: "BAD_REQUEST",             // 400
    VALIDATION_ERROR: "VALIDATION_ERROR",   // 400
    INVALID_INPUT: "INVALID_INPUT",         // 400
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND", // 404
    DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE", // 409
    METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED", // 405
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
