export const ERROR_CODES = {
    // 1. VALIDATION_ERRORS
    VALIDATION_ERROR: "VALIDATION_ERROR",
    INVALID_INPUT: "INVALID_INPUT",
    BAD_REQUEST: "BAD_REQUEST",

    // 2. BUSINESS_ERRORS
    RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
    DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
    METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",

    // 3. SECURITY_ERRORS
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    INVALID_TOKEN: "INVALID_TOKEN",

    // 4. INTERNAL_ERRORS
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    DATABASE_ERROR: "DATABASE_ERROR",
    TIMEOUT: "TIMEOUT",
    SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",

} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
